---
 - name: Create a new keypair
   ec2_key:
     profile: "{{aws_profile}}"
     name: k8s-key
     region: "{{aws_region}}"
   register: ec2_key

 - name: save private key
   copy:
     content: "{{ ec2_key.key.private_key }}"
     dest: "/root/k8s-key.pem"
     mode: 0400
   when: ec2_key.changed

 - name: ssh-add
   shell: ssh-add /root/k8s-key.pem 
   
