---
 - name: Wait for SSH to come up
   wait_for: timeout=45 
   
 - remote_user: ec2-user
   become: yes
   copy: 
     src: ./files/kubernetes.repo  
     dest: /etc/yum.repos.d/
   delegate_to: "{{ item.public_ip }}"  
   with_items: '{{ec2.instances}}'
